// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools
{
    public partial class DiscountCode : Pulumi.CustomResource
    {
        [Output("cartDiscounts")]
        public Output<ImmutableArray<string>> CartDiscounts { get; private set; } = null!;

        [Output("code")]
        public Output<string> Code { get; private set; } = null!;

        [Output("description")]
        public Output<ImmutableDictionary<string, object>?> Description { get; private set; } = null!;

        [Output("groups")]
        public Output<ImmutableArray<string>> Groups { get; private set; } = null!;

        [Output("isActive")]
        public Output<bool?> IsActive { get; private set; } = null!;

        [Output("maxApplications")]
        public Output<int?> MaxApplications { get; private set; } = null!;

        [Output("maxApplicationsPerCustomer")]
        public Output<int?> MaxApplicationsPerCustomer { get; private set; } = null!;

        [Output("name")]
        public Output<ImmutableDictionary<string, object>> Name { get; private set; } = null!;

        [Output("predicate")]
        public Output<string?> Predicate { get; private set; } = null!;

        [Output("validFrom")]
        public Output<string?> ValidFrom { get; private set; } = null!;

        [Output("validUntil")]
        public Output<string?> ValidUntil { get; private set; } = null!;

        [Output("version")]
        public Output<int> Version { get; private set; } = null!;


        /// <summary>
        /// Create a DiscountCode resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DiscountCode(string name, DiscountCodeArgs args, CustomResourceOptions? options = null)
            : base("commercetools:index/discountCode:DiscountCode", name, args ?? new DiscountCodeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DiscountCode(string name, Input<string> id, DiscountCodeState? state = null, CustomResourceOptions? options = null)
            : base("commercetools:index/discountCode:DiscountCode", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DiscountCode resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DiscountCode Get(string name, Input<string> id, DiscountCodeState? state = null, CustomResourceOptions? options = null)
        {
            return new DiscountCode(name, id, state, options);
        }
    }

    public sealed class DiscountCodeArgs : Pulumi.ResourceArgs
    {
        [Input("cartDiscounts", required: true)]
        private InputList<string>? _cartDiscounts;
        public InputList<string> CartDiscounts
        {
            get => _cartDiscounts ?? (_cartDiscounts = new InputList<string>());
            set => _cartDiscounts = value;
        }

        [Input("code", required: true)]
        public Input<string> Code { get; set; } = null!;

        [Input("description")]
        private InputMap<object>? _description;
        public InputMap<object> Description
        {
            get => _description ?? (_description = new InputMap<object>());
            set => _description = value;
        }

        [Input("groups")]
        private InputList<string>? _groups;
        public InputList<string> Groups
        {
            get => _groups ?? (_groups = new InputList<string>());
            set => _groups = value;
        }

        [Input("isActive")]
        public Input<bool>? IsActive { get; set; }

        [Input("maxApplications")]
        public Input<int>? MaxApplications { get; set; }

        [Input("maxApplicationsPerCustomer")]
        public Input<int>? MaxApplicationsPerCustomer { get; set; }

        [Input("name")]
        private InputMap<object>? _name;
        public InputMap<object> Name
        {
            get => _name ?? (_name = new InputMap<object>());
            set => _name = value;
        }

        [Input("predicate")]
        public Input<string>? Predicate { get; set; }

        [Input("validFrom")]
        public Input<string>? ValidFrom { get; set; }

        [Input("validUntil")]
        public Input<string>? ValidUntil { get; set; }

        public DiscountCodeArgs()
        {
        }
    }

    public sealed class DiscountCodeState : Pulumi.ResourceArgs
    {
        [Input("cartDiscounts")]
        private InputList<string>? _cartDiscounts;
        public InputList<string> CartDiscounts
        {
            get => _cartDiscounts ?? (_cartDiscounts = new InputList<string>());
            set => _cartDiscounts = value;
        }

        [Input("code")]
        public Input<string>? Code { get; set; }

        [Input("description")]
        private InputMap<object>? _description;
        public InputMap<object> Description
        {
            get => _description ?? (_description = new InputMap<object>());
            set => _description = value;
        }

        [Input("groups")]
        private InputList<string>? _groups;
        public InputList<string> Groups
        {
            get => _groups ?? (_groups = new InputList<string>());
            set => _groups = value;
        }

        [Input("isActive")]
        public Input<bool>? IsActive { get; set; }

        [Input("maxApplications")]
        public Input<int>? MaxApplications { get; set; }

        [Input("maxApplicationsPerCustomer")]
        public Input<int>? MaxApplicationsPerCustomer { get; set; }

        [Input("name")]
        private InputMap<object>? _name;
        public InputMap<object> Name
        {
            get => _name ?? (_name = new InputMap<object>());
            set => _name = value;
        }

        [Input("predicate")]
        public Input<string>? Predicate { get; set; }

        [Input("validFrom")]
        public Input<string>? ValidFrom { get; set; }

        [Input("validUntil")]
        public Input<string>? ValidUntil { get; set; }

        [Input("version")]
        public Input<int>? Version { get; set; }

        public DiscountCodeState()
        {
        }
    }
}
