// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools
{
    [CommercetoolsResourceType("commercetools:index/productSelection:ProductSelection")]
    public partial class ProductSelection : global::Pulumi.CustomResource
    {
        /// <summary>
        /// User-defined unique identifier of the ProductSelection.
        /// </summary>
        [Output("key")]
        public Output<string?> Key { get; private set; } = null!;

        /// <summary>
        /// Specifies in which way the Products are assigned to the ProductSelection.Currently, the only way of doing this is to
        /// specify each Product individually, either by including or excluding them explicitly.Default: Individual
        /// </summary>
        [Output("mode")]
        public Output<string> Mode { get; private set; } = null!;

        /// <summary>
        /// Name of the ProductSelection.
        /// </summary>
        [Output("name")]
        public Output<ImmutableDictionary<string, string>> Name { get; private set; } = null!;

        /// <summary>
        /// Current version of the ProductSelection.
        /// </summary>
        [Output("version")]
        public Output<int> Version { get; private set; } = null!;


        /// <summary>
        /// Create a ProductSelection resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProductSelection(string name, ProductSelectionArgs? args = null, CustomResourceOptions? options = null)
            : base("commercetools:index/productSelection:ProductSelection", name, args ?? new ProductSelectionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ProductSelection(string name, Input<string> id, ProductSelectionState? state = null, CustomResourceOptions? options = null)
            : base("commercetools:index/productSelection:ProductSelection", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProductSelection resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProductSelection Get(string name, Input<string> id, ProductSelectionState? state = null, CustomResourceOptions? options = null)
        {
            return new ProductSelection(name, id, state, options);
        }
    }

    public sealed class ProductSelectionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// User-defined unique identifier of the ProductSelection.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Specifies in which way the Products are assigned to the ProductSelection.Currently, the only way of doing this is to
        /// specify each Product individually, either by including or excluding them explicitly.Default: Individual
        /// </summary>
        [Input("mode")]
        public Input<string>? Mode { get; set; }

        [Input("name")]
        private InputMap<string>? _name;

        /// <summary>
        /// Name of the ProductSelection.
        /// </summary>
        public InputMap<string> Name
        {
            get => _name ?? (_name = new InputMap<string>());
            set => _name = value;
        }

        public ProductSelectionArgs()
        {
        }
        public static new ProductSelectionArgs Empty => new ProductSelectionArgs();
    }

    public sealed class ProductSelectionState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// User-defined unique identifier of the ProductSelection.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Specifies in which way the Products are assigned to the ProductSelection.Currently, the only way of doing this is to
        /// specify each Product individually, either by including or excluding them explicitly.Default: Individual
        /// </summary>
        [Input("mode")]
        public Input<string>? Mode { get; set; }

        [Input("name")]
        private InputMap<string>? _name;

        /// <summary>
        /// Name of the ProductSelection.
        /// </summary>
        public InputMap<string> Name
        {
            get => _name ?? (_name = new InputMap<string>());
            set => _name = value;
        }

        /// <summary>
        /// Current version of the ProductSelection.
        /// </summary>
        [Input("version")]
        public Input<int>? Version { get; set; }

        public ProductSelectionState()
        {
        }
        public static new ProductSelectionState Empty => new ProductSelectionState();
    }
}
