// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools
{
    public partial class ProjectSettings : Pulumi.CustomResource
    {
        [Output("countries")]
        public Output<ImmutableArray<string>> Countries { get; private set; } = null!;

        [Output("currencies")]
        public Output<ImmutableArray<string>> Currencies { get; private set; } = null!;

        [Output("externalOauth")]
        public Output<Outputs.ProjectSettingsExternalOauth?> ExternalOauth { get; private set; } = null!;

        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        [Output("languages")]
        public Output<ImmutableArray<string>> Languages { get; private set; } = null!;

        [Output("messages")]
        public Output<Outputs.ProjectSettingsMessages?> Messages { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("version")]
        public Output<int> Version { get; private set; } = null!;


        /// <summary>
        /// Create a ProjectSettings resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProjectSettings(string name, ProjectSettingsArgs? args = null, CustomResourceOptions? options = null)
            : base("commercetools:index/projectSettings:ProjectSettings", name, args ?? new ProjectSettingsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ProjectSettings(string name, Input<string> id, ProjectSettingsState? state = null, CustomResourceOptions? options = null)
            : base("commercetools:index/projectSettings:ProjectSettings", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProjectSettings resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProjectSettings Get(string name, Input<string> id, ProjectSettingsState? state = null, CustomResourceOptions? options = null)
        {
            return new ProjectSettings(name, id, state, options);
        }
    }

    public sealed class ProjectSettingsArgs : Pulumi.ResourceArgs
    {
        [Input("countries")]
        private InputList<string>? _countries;
        public InputList<string> Countries
        {
            get => _countries ?? (_countries = new InputList<string>());
            set => _countries = value;
        }

        [Input("currencies")]
        private InputList<string>? _currencies;
        public InputList<string> Currencies
        {
            get => _currencies ?? (_currencies = new InputList<string>());
            set => _currencies = value;
        }

        [Input("externalOauth")]
        public Input<Inputs.ProjectSettingsExternalOauthArgs>? ExternalOauth { get; set; }

        [Input("languages")]
        private InputList<string>? _languages;
        public InputList<string> Languages
        {
            get => _languages ?? (_languages = new InputList<string>());
            set => _languages = value;
        }

        [Input("messages")]
        public Input<Inputs.ProjectSettingsMessagesArgs>? Messages { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public ProjectSettingsArgs()
        {
        }
    }

    public sealed class ProjectSettingsState : Pulumi.ResourceArgs
    {
        [Input("countries")]
        private InputList<string>? _countries;
        public InputList<string> Countries
        {
            get => _countries ?? (_countries = new InputList<string>());
            set => _countries = value;
        }

        [Input("currencies")]
        private InputList<string>? _currencies;
        public InputList<string> Currencies
        {
            get => _currencies ?? (_currencies = new InputList<string>());
            set => _currencies = value;
        }

        [Input("externalOauth")]
        public Input<Inputs.ProjectSettingsExternalOauthGetArgs>? ExternalOauth { get; set; }

        [Input("key")]
        public Input<string>? Key { get; set; }

        [Input("languages")]
        private InputList<string>? _languages;
        public InputList<string> Languages
        {
            get => _languages ?? (_languages = new InputList<string>());
            set => _languages = value;
        }

        [Input("messages")]
        public Input<Inputs.ProjectSettingsMessagesGetArgs>? Messages { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("version")]
        public Input<int>? Version { get; set; }

        public ProjectSettingsState()
        {
        }
    }
}
