// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Pulumi.Commercetools
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("commercetools");

        private static readonly __Value<string?> _apiUrl = new __Value<string?>(() => __config.Get("apiUrl"));
        /// <summary>
        /// The API URL of the commercetools platform. https://docs.commercetools.com/http-api
        /// </summary>
        public static string? ApiUrl
        {
            get => _apiUrl.Get();
            set => _apiUrl.Set(value);
        }

        private static readonly __Value<string?> _clientId = new __Value<string?>(() => __config.Get("clientId"));
        /// <summary>
        /// The OAuth Client ID for a commercetools platform project. https://docs.commercetools.com/http-api-authorization
        /// </summary>
        public static string? ClientId
        {
            get => _clientId.Get();
            set => _clientId.Set(value);
        }

        private static readonly __Value<string?> _clientSecret = new __Value<string?>(() => __config.Get("clientSecret"));
        /// <summary>
        /// The OAuth Client Secret for a commercetools platform project. https://docs.commercetools.com/http-api-authorization
        /// </summary>
        public static string? ClientSecret
        {
            get => _clientSecret.Get();
            set => _clientSecret.Set(value);
        }

        private static readonly __Value<string?> _projectKey = new __Value<string?>(() => __config.Get("projectKey"));
        /// <summary>
        /// The project key of commercetools platform project. https://docs.commercetools.com/getting-started
        /// </summary>
        public static string? ProjectKey
        {
            get => _projectKey.Get();
            set => _projectKey.Set(value);
        }

        private static readonly __Value<string?> _scopes = new __Value<string?>(() => __config.Get("scopes"));
        /// <summary>
        /// A list as string of OAuth scopes assigned to a project key, to access resources in a commercetools platform project.
        /// https://docs.commercetools.com/http-api-authorization
        /// </summary>
        public static string? Scopes
        {
            get => _scopes.Get();
            set => _scopes.Set(value);
        }

        private static readonly __Value<string?> _tokenUrl = new __Value<string?>(() => __config.Get("tokenUrl"));
        /// <summary>
        /// The authentication URL of the commercetools platform. https://docs.commercetools.com/http-api-authorization
        /// </summary>
        public static string? TokenUrl
        {
            get => _tokenUrl.Get();
            set => _tokenUrl.Set(value);
        }

    }
}
