// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package commercetools

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-commercetools/sdk/go/commercetools/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the commercetools package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// The API URL of the commercetools platform. https://docs.commercetools.com/http-api
	ApiUrl pulumi.StringPtrOutput `pulumi:"apiUrl"`
	// The OAuth Client ID for a commercetools platform project. https://docs.commercetools.com/http-api-authorization
	ClientId pulumi.StringPtrOutput `pulumi:"clientId"`
	// The OAuth Client Secret for a commercetools platform project. https://docs.commercetools.com/http-api-authorization
	ClientSecret pulumi.StringPtrOutput `pulumi:"clientSecret"`
	// The project key of commercetools platform project. https://docs.commercetools.com/getting-started
	ProjectKey pulumi.StringPtrOutput `pulumi:"projectKey"`
	// A list as string of OAuth scopes assigned to a project key, to access resources in a commercetools platform project.
	// https://docs.commercetools.com/http-api-authorization
	Scopes pulumi.StringPtrOutput `pulumi:"scopes"`
	// The authentication URL of the commercetools platform. https://docs.commercetools.com/http-api-authorization
	TokenUrl pulumi.StringPtrOutput `pulumi:"tokenUrl"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.ClientId != nil {
		args.ClientId = pulumi.ToSecret(args.ClientId).(pulumi.StringPtrInput)
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringPtrInput)
	}
	if args.ProjectKey != nil {
		args.ProjectKey = pulumi.ToSecret(args.ProjectKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientId",
		"clientSecret",
		"projectKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:commercetools", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The API URL of the commercetools platform. https://docs.commercetools.com/http-api
	ApiUrl *string `pulumi:"apiUrl"`
	// The OAuth Client ID for a commercetools platform project. https://docs.commercetools.com/http-api-authorization
	ClientId *string `pulumi:"clientId"`
	// The OAuth Client Secret for a commercetools platform project. https://docs.commercetools.com/http-api-authorization
	ClientSecret *string `pulumi:"clientSecret"`
	// The project key of commercetools platform project. https://docs.commercetools.com/getting-started
	ProjectKey *string `pulumi:"projectKey"`
	// A list as string of OAuth scopes assigned to a project key, to access resources in a commercetools platform project.
	// https://docs.commercetools.com/http-api-authorization
	Scopes *string `pulumi:"scopes"`
	// The authentication URL of the commercetools platform. https://docs.commercetools.com/http-api-authorization
	TokenUrl *string `pulumi:"tokenUrl"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The API URL of the commercetools platform. https://docs.commercetools.com/http-api
	ApiUrl pulumi.StringPtrInput
	// The OAuth Client ID for a commercetools platform project. https://docs.commercetools.com/http-api-authorization
	ClientId pulumi.StringPtrInput
	// The OAuth Client Secret for a commercetools platform project. https://docs.commercetools.com/http-api-authorization
	ClientSecret pulumi.StringPtrInput
	// The project key of commercetools platform project. https://docs.commercetools.com/getting-started
	ProjectKey pulumi.StringPtrInput
	// A list as string of OAuth scopes assigned to a project key, to access resources in a commercetools platform project.
	// https://docs.commercetools.com/http-api-authorization
	Scopes pulumi.StringPtrInput
	// The authentication URL of the commercetools platform. https://docs.commercetools.com/http-api-authorization
	TokenUrl pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The API URL of the commercetools platform. https://docs.commercetools.com/http-api
func (o ProviderOutput) ApiUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiUrl }).(pulumi.StringPtrOutput)
}

// The OAuth Client ID for a commercetools platform project. https://docs.commercetools.com/http-api-authorization
func (o ProviderOutput) ClientId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ClientId }).(pulumi.StringPtrOutput)
}

// The OAuth Client Secret for a commercetools platform project. https://docs.commercetools.com/http-api-authorization
func (o ProviderOutput) ClientSecret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ClientSecret }).(pulumi.StringPtrOutput)
}

// The project key of commercetools platform project. https://docs.commercetools.com/getting-started
func (o ProviderOutput) ProjectKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ProjectKey }).(pulumi.StringPtrOutput)
}

// A list as string of OAuth scopes assigned to a project key, to access resources in a commercetools platform project.
// https://docs.commercetools.com/http-api-authorization
func (o ProviderOutput) Scopes() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Scopes }).(pulumi.StringPtrOutput)
}

// The authentication URL of the commercetools platform. https://docs.commercetools.com/http-api-authorization
func (o ProviderOutput) TokenUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.TokenUrl }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
