// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Outputs
{

    [OutputType]
    public sealed class AttributeGroupAttribute
    {
        /// <summary>
        /// The Attribute's name as given in its AttributeDefinition.
        /// </summary>
        public readonly string Key;

        [OutputConstructor]
        private AttributeGroupAttribute(string key)
        {
            Key = key;
        }
    }
}
