// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Outputs
{

    [OutputType]
    public sealed class CartDiscountValue
    {
        public readonly string? DistributionChannelId;
        public readonly ImmutableArray<Outputs.CartDiscountValueMoney> Monies;
        public readonly int? Permyriad;
        public readonly string? ProductId;
        public readonly string? SupplyChannelId;
        public readonly string Type;
        public readonly int? VariantId;

        [OutputConstructor]
        private CartDiscountValue(
            string? distributionChannelId,

            ImmutableArray<Outputs.CartDiscountValueMoney> monies,

            int? permyriad,

            string? productId,

            string? supplyChannelId,

            string type,

            int? variantId)
        {
            DistributionChannelId = distributionChannelId;
            Monies = monies;
            Permyriad = permyriad;
            ProductId = productId;
            SupplyChannelId = supplyChannelId;
            Type = type;
            VariantId = variantId;
        }
    }
}
