// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Outputs
{

    [OutputType]
    public sealed class CategoryAssetSource
    {
        public readonly string? ContentType;
        public readonly Outputs.CategoryAssetSourceDimensions? Dimensions;
        /// <summary>
        /// Unique identifier, must be unique within the Asset
        /// </summary>
        public readonly string? Key;
        public readonly string Uri;

        [OutputConstructor]
        private CategoryAssetSource(
            string? contentType,

            Outputs.CategoryAssetSourceDimensions? dimensions,

            string? key,

            string uri)
        {
            ContentType = contentType;
            Dimensions = dimensions;
            Key = key;
            Uri = uri;
        }
    }
}
