// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Outputs
{

    [OutputType]
    public sealed class CategoryAsset
    {
        public readonly ImmutableDictionary<string, object>? Description;
        public readonly string? Id;
        /// <summary>
        /// Optional User-defined identifier for the asset. Asset keys are unique inside their container (in this case the category)
        /// </summary>
        public readonly string? Key;
        public readonly ImmutableDictionary<string, object> Name;
        /// <summary>
        /// Array of AssetSource, Has at least one entry
        /// </summary>
        public readonly ImmutableArray<Outputs.CategoryAssetSource> Sources;
        public readonly ImmutableArray<string> Tags;

        [OutputConstructor]
        private CategoryAsset(
            ImmutableDictionary<string, object>? description,

            string? id,

            string? key,

            ImmutableDictionary<string, object> name,

            ImmutableArray<Outputs.CategoryAssetSource> sources,

            ImmutableArray<string> tags)
        {
            Description = description;
            Id = id;
            Key = key;
            Name = name;
            Sources = sources;
            Tags = tags;
        }
    }
}
