// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Outputs
{

    [OutputType]
    public sealed class ProductTypeAttribute
    {
        public readonly string? Constraint;
        public readonly string? InputHint;
        public readonly ImmutableDictionary<string, object>? InputTip;
        public readonly ImmutableDictionary<string, object> Label;
        public readonly string Name;
        public readonly bool? Required;
        public readonly bool? Searchable;
        public readonly Outputs.ProductTypeAttributeType Type;

        [OutputConstructor]
        private ProductTypeAttribute(
            string? constraint,

            string? inputHint,

            ImmutableDictionary<string, object>? inputTip,

            ImmutableDictionary<string, object> label,

            string name,

            bool? required,

            bool? searchable,

            Outputs.ProductTypeAttributeType type)
        {
            Constraint = constraint;
            InputHint = inputHint;
            InputTip = inputTip;
            Label = label;
            Name = name;
            Required = required;
            Searchable = searchable;
            Type = type;
        }
    }
}
