// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Outputs
{

    [OutputType]
    public sealed class ProjectSettingsShippingRateCartClassificationValue
    {
        /// <summary>
        /// [Resource Type ID](https://docs.commercetools.com/api/projects/Projects#changeProject)
        /// </summary>
        public readonly string Key;
        public readonly ImmutableDictionary<string, string>? Label;

        [OutputConstructor]
        private ProjectSettingsShippingRateCartClassificationValue(
            string key,

            ImmutableDictionary<string, string>? label)
        {
            Key = key;
            Label = label;
        }
    }
}
