// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Outputs
{

    [OutputType]
    public sealed class ProjectSettingsMessages
    {
        public readonly int? DeleteDaysAfterCreation;
        public readonly bool? Enabled;

        [OutputConstructor]
        private ProjectSettingsMessages(
            int? deleteDaysAfterCreation,

            bool? enabled)
        {
            DeleteDaysAfterCreation = deleteDaysAfterCreation;
            Enabled = enabled;
        }
    }
}
