// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Outputs
{

    [OutputType]
    public sealed class SubscriptionMessage
    {
        /// <summary>
        /// [Resource Type ID](https://docs.commercetools.com/api/projects/subscriptions#changesubscription)
        /// </summary>
        public readonly string ResourceTypeId;
        /// <summary>
        /// types must contain valid message types for this resource, for example for resource type product the message type ProductPublished is valid. If no types of messages are given, the subscription is valid for all messages of this resource
        /// </summary>
        public readonly ImmutableArray<string> Types;

        [OutputConstructor]
        private SubscriptionMessage(
            string resourceTypeId,

            ImmutableArray<string> types)
        {
            ResourceTypeId = resourceTypeId;
            Types = types;
        }
    }
}
