// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Outputs
{

    [OutputType]
    public sealed class TypeFieldTypeElementType2
    {
        /// <summary>
        /// Localized values for the `lenum` type.
        /// </summary>
        public readonly ImmutableArray<Outputs.TypeFieldTypeElementType2LocalizedValue> LocalizedValues;
        /// <summary>
        /// Name of the field type. Some types require extra fields to be set. Note that changing the type after creating is not supported. You need to delete the attribute and re-add it.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Resource type the Custom Field can reference. Required when type is `Reference`
        /// </summary>
        public readonly string? ReferenceTypeId;
        /// <summary>
        /// Values for the `enum` type.
        /// </summary>
        public readonly ImmutableArray<Outputs.TypeFieldTypeElementType2Value> Values;

        [OutputConstructor]
        private TypeFieldTypeElementType2(
            ImmutableArray<Outputs.TypeFieldTypeElementType2LocalizedValue> localizedValues,

            string name,

            string? referenceTypeId,

            ImmutableArray<Outputs.TypeFieldTypeElementType2Value> values)
        {
            LocalizedValues = localizedValues;
            Name = name;
            ReferenceTypeId = referenceTypeId;
            Values = values;
        }
    }
}
