// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Outputs
{

    [OutputType]
    public sealed class TypeField
    {
        public readonly string? InputHint;
        public readonly ImmutableDictionary<string, object> Label;
        public readonly string Name;
        public readonly bool? Required;
        public readonly Outputs.TypeFieldType Type;

        [OutputConstructor]
        private TypeField(
            string? inputHint,

            ImmutableDictionary<string, object> label,

            string name,

            bool? required,

            Outputs.TypeFieldType type)
        {
            InputHint = inputHint;
            Label = label;
            Name = name;
            Required = required;
            Type = type;
        }
    }
}
