// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Inputs
{

    public sealed class ApiExtensionDestinationArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessKey")]
        public Input<string>? AccessKey { get; set; }

        [Input("accessSecret")]
        private Input<string>? _accessSecret;
        public Input<string>? AccessSecret
        {
            get => _accessSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accessSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("arn")]
        public Input<string>? Arn { get; set; }

        [Input("authorizationHeader")]
        public Input<string>? AuthorizationHeader { get; set; }

        [Input("azureAuthentication")]
        public Input<string>? AzureAuthentication { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        [Input("url")]
        public Input<string>? Url { get; set; }

        public ApiExtensionDestinationArgs()
        {
        }
        public static new ApiExtensionDestinationArgs Empty => new ApiExtensionDestinationArgs();
    }
}
