// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Inputs
{

    public sealed class ChannelGeolocationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("coordinates", required: true)]
        private InputList<double>? _coordinates;
        public InputList<double> Coordinates
        {
            get => _coordinates ?? (_coordinates = new InputList<double>());
            set => _coordinates = value;
        }

        public ChannelGeolocationGetArgs()
        {
        }
        public static new ChannelGeolocationGetArgs Empty => new ChannelGeolocationGetArgs();
    }
}
