// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Inputs
{

    public sealed class ProductDiscountValueGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("monies")]
        private InputList<Inputs.ProductDiscountValueMoneyGetArgs>? _monies;

        /// <summary>
        /// Absolute discount specific fields
        /// </summary>
        public InputList<Inputs.ProductDiscountValueMoneyGetArgs> Monies
        {
            get => _monies ?? (_monies = new InputList<Inputs.ProductDiscountValueMoneyGetArgs>());
            set => _monies = value;
        }

        /// <summary>
        /// Relative discount specific fields
        /// </summary>
        [Input("permyriad")]
        public Input<int>? Permyriad { get; set; }

        /// <summary>
        /// Currently supports absolute/relative/external
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public ProductDiscountValueGetArgs()
        {
        }
        public static new ProductDiscountValueGetArgs Empty => new ProductDiscountValueGetArgs();
    }
}
