// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Commercetools.Inputs
{

    public sealed class ShippingZoneRateShippingRatePriceTierGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("minimumCentAmount")]
        public Input<int>? MinimumCentAmount { get; set; }

        [Input("price")]
        public Input<Inputs.ShippingZoneRateShippingRatePriceTierPriceGetArgs>? Price { get; set; }

        [Input("priceFunction")]
        public Input<Inputs.ShippingZoneRateShippingRatePriceTierPriceFunctionGetArgs>? PriceFunction { get; set; }

        [Input("score")]
        public Input<int>? Score { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        [Input("value")]
        public Input<string>? Value { get; set; }

        public ShippingZoneRateShippingRatePriceTierGetArgs()
        {
        }
        public static new ShippingZoneRateShippingRatePriceTierGetArgs Empty => new ShippingZoneRateShippingRatePriceTierGetArgs();
    }
}
