// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CustomObject extends pulumi.CustomResource {
    /**
     * Get an existing CustomObject resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomObjectState, opts?: pulumi.CustomResourceOptions): CustomObject {
        return new CustomObject(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'commercetools:index/customObject:CustomObject';

    /**
     * Returns true if the given object is an instance of CustomObject.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomObject {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomObject.__pulumiType;
    }

    /**
     * A namespace to group custom objects matching the pattern '[-_~.a-zA-Z0-9]+'
     */
    public readonly container!: pulumi.Output<string>;
    /**
     * String matching the pattern '[-_~.a-zA-Z0-9]+'
     */
    public readonly key!: pulumi.Output<string>;
    /**
     * JSON types Number, String, Boolean, Array, Object
     */
    public readonly value!: pulumi.Output<string>;
    public /*out*/ readonly version!: pulumi.Output<number>;

    /**
     * Create a CustomObject resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomObjectArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomObjectArgs | CustomObjectState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomObjectState | undefined;
            inputs["container"] = state ? state.container : undefined;
            inputs["key"] = state ? state.key : undefined;
            inputs["value"] = state ? state.value : undefined;
            inputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as CustomObjectArgs | undefined;
            if ((!args || args.container === undefined) && !opts.urn) {
                throw new Error("Missing required property 'container'");
            }
            if ((!args || args.key === undefined) && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if ((!args || args.value === undefined) && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            inputs["container"] = args ? args.container : undefined;
            inputs["key"] = args ? args.key : undefined;
            inputs["value"] = args ? args.value : undefined;
            inputs["version"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(CustomObject.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CustomObject resources.
 */
export interface CustomObjectState {
    /**
     * A namespace to group custom objects matching the pattern '[-_~.a-zA-Z0-9]+'
     */
    container?: pulumi.Input<string>;
    /**
     * String matching the pattern '[-_~.a-zA-Z0-9]+'
     */
    key?: pulumi.Input<string>;
    /**
     * JSON types Number, String, Boolean, Array, Object
     */
    value?: pulumi.Input<string>;
    version?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a CustomObject resource.
 */
export interface CustomObjectArgs {
    /**
     * A namespace to group custom objects matching the pattern '[-_~.a-zA-Z0-9]+'
     */
    container: pulumi.Input<string>;
    /**
     * String matching the pattern '[-_~.a-zA-Z0-9]+'
     */
    key: pulumi.Input<string>;
    /**
     * JSON types Number, String, Boolean, Array, Object
     */
    value: pulumi.Input<string>;
}
