// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ShippingZone extends pulumi.CustomResource {
    /**
     * Get an existing ShippingZone resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ShippingZoneState, opts?: pulumi.CustomResourceOptions): ShippingZone {
        return new ShippingZone(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'commercetools:index/shippingZone:ShippingZone';

    /**
     * Returns true if the given object is an instance of ShippingZone.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ShippingZone {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ShippingZone.__pulumiType;
    }

    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * User-specific unique identifier for a zone. Must be unique across a project
     */
    public readonly key!: pulumi.Output<string | undefined>;
    /**
     * [Location](https://docs.commercetoolstools.pi/projects/zones#location)
     */
    public readonly locations!: pulumi.Output<outputs.ShippingZoneLocation[] | undefined>;
    public readonly name!: pulumi.Output<string>;
    public /*out*/ readonly version!: pulumi.Output<number>;

    /**
     * Create a ShippingZone resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ShippingZoneArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ShippingZoneArgs | ShippingZoneState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ShippingZoneState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["key"] = state ? state.key : undefined;
            resourceInputs["locations"] = state ? state.locations : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as ShippingZoneArgs | undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["key"] = args ? args.key : undefined;
            resourceInputs["locations"] = args ? args.locations : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ShippingZone.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ShippingZone resources.
 */
export interface ShippingZoneState {
    description?: pulumi.Input<string>;
    /**
     * User-specific unique identifier for a zone. Must be unique across a project
     */
    key?: pulumi.Input<string>;
    /**
     * [Location](https://docs.commercetoolstools.pi/projects/zones#location)
     */
    locations?: pulumi.Input<pulumi.Input<inputs.ShippingZoneLocation>[]>;
    name?: pulumi.Input<string>;
    version?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a ShippingZone resource.
 */
export interface ShippingZoneArgs {
    description?: pulumi.Input<string>;
    /**
     * User-specific unique identifier for a zone. Must be unique across a project
     */
    key?: pulumi.Input<string>;
    /**
     * [Location](https://docs.commercetoolstools.pi/projects/zones#location)
     */
    locations?: pulumi.Input<pulumi.Input<inputs.ShippingZoneLocation>[]>;
    name?: pulumi.Input<string>;
}
