// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Subscription extends pulumi.CustomResource {
    /**
     * Get an existing Subscription resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SubscriptionState, opts?: pulumi.CustomResourceOptions): Subscription {
        return new Subscription(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'commercetools:index/subscription:Subscription';

    /**
     * Returns true if the given object is an instance of Subscription.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Subscription {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Subscription.__pulumiType;
    }

    public readonly changes!: pulumi.Output<outputs.SubscriptionChange[] | undefined>;
    public readonly destination!: pulumi.Output<outputs.SubscriptionDestination | undefined>;
    public readonly format!: pulumi.Output<outputs.SubscriptionFormat | undefined>;
    public readonly key!: pulumi.Output<string | undefined>;
    public readonly messages!: pulumi.Output<outputs.SubscriptionMessage[] | undefined>;
    public /*out*/ readonly version!: pulumi.Output<number>;

    /**
     * Create a Subscription resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SubscriptionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SubscriptionArgs | SubscriptionState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as SubscriptionState | undefined;
            inputs["changes"] = state ? state.changes : undefined;
            inputs["destination"] = state ? state.destination : undefined;
            inputs["format"] = state ? state.format : undefined;
            inputs["key"] = state ? state.key : undefined;
            inputs["messages"] = state ? state.messages : undefined;
            inputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as SubscriptionArgs | undefined;
            inputs["changes"] = args ? args.changes : undefined;
            inputs["destination"] = args ? args.destination : undefined;
            inputs["format"] = args ? args.format : undefined;
            inputs["key"] = args ? args.key : undefined;
            inputs["messages"] = args ? args.messages : undefined;
            inputs["version"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Subscription.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Subscription resources.
 */
export interface SubscriptionState {
    readonly changes?: pulumi.Input<pulumi.Input<inputs.SubscriptionChange>[]>;
    readonly destination?: pulumi.Input<inputs.SubscriptionDestination>;
    readonly format?: pulumi.Input<inputs.SubscriptionFormat>;
    readonly key?: pulumi.Input<string>;
    readonly messages?: pulumi.Input<pulumi.Input<inputs.SubscriptionMessage>[]>;
    readonly version?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Subscription resource.
 */
export interface SubscriptionArgs {
    readonly changes?: pulumi.Input<pulumi.Input<inputs.SubscriptionChange>[]>;
    readonly destination?: pulumi.Input<inputs.SubscriptionDestination>;
    readonly format?: pulumi.Input<inputs.SubscriptionFormat>;
    readonly key?: pulumi.Input<string>;
    readonly messages?: pulumi.Input<pulumi.Input<inputs.SubscriptionMessage>[]>;
}
